// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlvlorqapxfdisoksjah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsdmxvcnFhcHhmZGlzb2tzamFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NDgyMjYsImV4cCI6MjA3NzEyNDIyNn0.g1viMSsoUrlR3hxhadFLtgNK-d1O45EijYC5pGq9dvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});